apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mq-service-web
  namespace: {{ .Values.nameSpace }}-{{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.serviceWeb.type }}
  ports:
    - port: {{ .Values.serviceWeb.port }}
      targetPort: {{ .Values.serviceWeb.port }}
  selector:
    app: {{ .Release.Name }}